import { Provider } from "@/components/ui/provider";
import type { Metadata } from "next";
import { Sidebar } from "./_components/sidebar";
import { TopMenu } from "./_components/top-menu";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning>
      <body>
        <Provider>
          <TopMenu />
          <div style={{ display: "flex" }}>
            <Sidebar />
            <main style={{ flexGrow: 1 }}>{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
